# Generated by Django 4.2 on 2023-12-29 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graphAPP1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
