# Generated by Django 4.2 on 2023-12-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphAPP1', '0002_graph_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=150)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=250)),
                ('repairIn5d', models.IntegerField()),
                ('deviceType', models.CharField(max_length=50)),
                ('servicePoint', models.CharField(max_length=50)),
                ('deviceCat', models.CharField(max_length=50)),
                ('warranty', models.IntegerField()),
            ],
        ),
    ]
